---
- name: install selinux tools
  package:
    name: policycoreutils-python
    state: present

- name: remove existing selinux policy
  command: semodule -r nginx
  failed_when: false

- name: copy selinux type enforcement file
  template:
    src: nginx.te
    dest: /tmp/nginx.te

- name: compile selinux module
  command: checkmodule -M -m -o /tmp/nginx.mod /tmp/nginx.te

- name: create selinux policy package
  command: semodule_package -o /tmp/nginx.pp -m /tmp/nginx.mod

- name: load selinux policy
  command: semodule -i /tmp/nginx.pp

- name: clean up selinux src
  file:
    path: /tmp/nginx.*
    state: absent
